apiVersion : apps/v1
kind : Deployment
metadata:
  name : shine-deployment
  labels:
    app : httpd
spec:
  template:
    metadata:
      labels:
        app : httpd
    spec:
      containers:
        - name: shine
          image: devtechieops/s1:1.0
          ports:
            - containerPort: 80
  selector:   
    matchLabels:
      app : httpd
